### ISSUE TITLE
seems to crash very early with current version of the game 0.15.7

### ISSUE THREAD

**Issue by gsgatlin** [MCMrARM/mcpelauncher-linux#70]
loading MCPE
oslib: /usr/lib/libGLESv2.so: 151915272
oslib: /home/gsgatlin/mcpe/mcpelauncher-linux/libs/native/libfmod.so.8.2: 151917256
loaded MCPE (at 4127862784)
apply patches
original: 85 87 86 83 232
post patch: 233 248 62 207 17
original: 85 87 86 83 232
post patch: 233 94 109 207 17
original: 85 137 229 87 86
post patch: 233 40 160 202 17
original: 87 86 83 232 136
post patch: 233 246 108 207 17
Signal 11 received
Getting stacktrace...
Backtrace elements: 6
#0 ./mcpelauncher(_Z12handleSignali+0x3c) [0x8062914]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf76edce0]
#2 ./mcpelauncher(_Z20patchCallInstructionPvS_b+0x1a) [0x8062316]
#3 ./mcpelauncher(main+0x136f) [0x8063f30]
#4 /lib/libc.so.6(__libc_start_main+0xf5) [0xf7187545]
#5 ./mcpelauncher() [0x80550d1]

...

OS is fedora 23.  Thanks for any ideas anyone has.

**Comment by guppy42** [comment]
+1
Confirmed on Ubuntu 16.04 ( gcc 5.4 )

**Comment by guppy42** [comment]
Problem identified;

nm -D libs/libminecraftpe.so | grep -i crossplat

gives no results so lin 496-500 that attempts to patch '_ZN9crossplat10threadpool16detach_from_javaEPv' & '_ZN9crossplat11get_jvm_envEv' will fail


patching the code to check for null addresses reveals that

_ZN4xbox8services20xbox_live_app_config24get_app_config_singletonEv
_ZN4xbox8services20xbox_live_app_config11set_sandboxESs

are also gone, since the code contains no hit of how the original author arrived at these function figuring out how to fix the code is not going to be an easy task

**Comment by stayandwait** [comment]
The launcher code is a bit dated. Seams to only support 0.15.0

**Comment by neuhaus** [comment]
Has this issue been closed because it has been fixed?

**Comment by MCMrARM** [comment]
The issue has been closed because it's old and the issue doens't happen with 1.0.0
